// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_LampSensorComp_create_hook(lv_obj_t * comp)
{
}
