// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_LAMPSENSORCOMP_H
#define _UI_COMP_LAMPSENSORCOMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LampSensorComp
#define UI_COMP_LAMPSENSORCOMP_LAMPSENSORCOMP 0
#define UI_COMP_LAMPSENSORCOMP_IMAGE13 1
#define UI_COMP_LAMPSENSORCOMP_LABEL11 2
#define UI_COMP_LAMPSENSORCOMP_LABEL4 3
#define UI_COMP_LAMPSENSORCOMP_BUTTON9 4
#define UI_COMP_LAMPSENSORCOMP_BUTTON9_IMAGE1 5
#define UI_COMP_LAMPSENSORCOMP_BUTTON1 6
#define UI_COMP_LAMPSENSORCOMP_BUTTON1_IMAGE10 7
#define UI_COMP_LAMPSENSORCOMP_BUTTON5 8
#define UI_COMP_LAMPSENSORCOMP_BUTTON5_IMAGE11 9
#define _UI_COMP_LAMPSENSORCOMP_NUM 10
lv_obj_t * ui_LampSensorComp_create(lv_obj_t * comp_parent);
void ui_event_comp_LampSensorComp_Button1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
