// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_LampSensorComp_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_LampSensorComp = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        swichoffbtnCB(e);
    }
}

// COMPONENT LampSensorComp

lv_obj_t * ui_LampSensorComp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_LampSensorComp;
    cui_LampSensorComp = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_LampSensorComp);
    lv_obj_set_width(cui_LampSensorComp, 400);
    lv_obj_set_height(cui_LampSensorComp, 96);
    lv_obj_set_x(cui_LampSensorComp, 0);
    lv_obj_set_y(cui_LampSensorComp, -1);
    lv_obj_set_align(cui_LampSensorComp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_LampSensorComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_LampSensorComp, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_LampSensorComp, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_LampSensorComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_LampSensorComp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_LampSensorComp, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image13;
    cui_Image13 = lv_image_create(cui_LampSensorComp);
    lv_image_set_src(cui_Image13, &ui_img_icons_lightbulb_off_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(cui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image13, 6);
    lv_obj_set_y(cui_Image13, 16);
    lv_obj_remove_flag(cui_Image13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label11;
    cui_Label11 = lv_label_create(cui_LampSensorComp);
    lv_obj_set_width(cui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label11, 0);
    lv_obj_set_y(cui_Label11, -36);
    lv_obj_set_align(cui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label11, "лампа");
    lv_obj_set_style_text_color(cui_Label11, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label11, &ui_font_RobotoMedium14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_LampSensorComp);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label4, 0);
    lv_obj_set_y(cui_Label4, 36);
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "комната");
    lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label4, &ui_font_RobotoBold12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button9;
    cui_Button9 = lv_button_create(cui_LampSensorComp);
    lv_obj_set_width(cui_Button9, 36);
    lv_obj_set_height(cui_Button9, 36);
    lv_obj_set_x(cui_Button9, -6);
    lv_obj_set_y(cui_Button9, 0);
    lv_obj_set_align(cui_Button9, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button9, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_image_create(cui_Button9);
    lv_image_set_src(cui_Image1, &ui_img_icons_settings_24dp_61c6ce_fill0_wght200_grad0_opsz24_png);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_button_create(cui_LampSensorComp);
    lv_obj_set_width(cui_Button1, 48);
    lv_obj_set_height(cui_Button1, 48);
    lv_obj_set_x(cui_Button1, -32);
    lv_obj_set_y(cui_Button1, 0);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button1, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image10;
    cui_Image10 = lv_image_create(cui_Button1);
    lv_image_set_src(cui_Image10, &ui_img_icons_power_on_circle_36dp_61c6ce_fill1_wght200_grad0_opsz40_png);
    lv_obj_set_width(cui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Image10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Button5;
    cui_Button5 = lv_button_create(cui_LampSensorComp);
    lv_obj_set_width(cui_Button5, 48);
    lv_obj_set_height(cui_Button5, 48);
    lv_obj_set_x(cui_Button5, 32);
    lv_obj_set_y(cui_Button5, 0);
    lv_obj_set_align(cui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button5, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image11;
    cui_Image11 = lv_image_create(cui_Button5);
    lv_image_set_src(cui_Image11, &ui_img_icons_power_off_circle_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(cui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Image11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LAMPSENSORCOMP_NUM);
    children[UI_COMP_LAMPSENSORCOMP_LAMPSENSORCOMP] = cui_LampSensorComp;
    children[UI_COMP_LAMPSENSORCOMP_IMAGE13] = cui_Image13;
    children[UI_COMP_LAMPSENSORCOMP_LABEL11] = cui_Label11;
    children[UI_COMP_LAMPSENSORCOMP_LABEL4] = cui_Label4;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON9] = cui_Button9;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON9_IMAGE1] = cui_Image1;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON1] = cui_Button1;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON1_IMAGE10] = cui_Image10;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON5] = cui_Button5;
    children[UI_COMP_LAMPSENSORCOMP_BUTTON5_IMAGE11] = cui_Image11;
    lv_obj_add_event_cb(cui_LampSensorComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LampSensorComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button1, ui_event_comp_LampSensorComp_Button1, LV_EVENT_ALL, children);
    ui_comp_LampSensorComp_create_hook(cui_LampSensorComp);
    return cui_LampSensorComp;
}

