// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_RoomsScreenAddRoomBtn;
lv_obj_t * uic_RoomsScreenRoomsContainer;
lv_obj_t * uic_RoomsScreenMainPanel;
lv_obj_t * uic_RoomsScreenSettingsButton;
lv_obj_t * uic_RoomsScreenScenesButton;
lv_obj_t * uic_RoomsScreenGroupsButton;
lv_obj_t * uic_RoomsScreenRoomsButton;
lv_obj_t * uic_RoomsScreenHomeButton;
lv_obj_t * uic_RoomsScreenTopPanel;
lv_obj_t * uic_RoomsScreenMicOpenBtn;
lv_obj_t * uic_RoomsScreenKeyboardOpenBtn;
lv_obj_t * uic_RoomsScreen;
lv_obj_t * ui_RoomsScreen = NULL;
lv_obj_t * ui_RoomsScreenMainLabel1 = NULL;
lv_obj_t * ui_RoomsScreenKeyboardOpenBtn = NULL;
lv_obj_t * ui_RoomsScreenMicOpenBtn = NULL;
lv_obj_t * ui_RoomsScreenTopPanel = NULL;
lv_obj_t * ui_RoomsScreenHomeButton = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_RoomsScreenRoomsButton = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_RoomsScreenGroupsButton = NULL;
lv_obj_t * ui_Image31 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_RoomsScreenScenesButton = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_RoomsScreenSettingsButton = NULL;
lv_obj_t * ui_Image33 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_RoomsScreenMainPanel = NULL;
lv_obj_t * ui_RoomsScreenRoomsContainer = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Image35 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Image36 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Button33 = NULL;
lv_obj_t * ui_Image37 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_RoomsScreenAddRoomBtn = NULL;
lv_obj_t * ui_Image34 = NULL;
lv_obj_t * ui_Label41 = NULL;
// event funtions
void ui_event_RoomsScreenHomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_RoomsScreen_screen_init(void)
{
    ui_RoomsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RoomsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RoomsScreenMainLabel1 = lv_label_create(ui_RoomsScreen);
    lv_obj_set_width(ui_RoomsScreenMainLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RoomsScreenMainLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RoomsScreenMainLabel1, 0);
    lv_obj_set_y(ui_RoomsScreenMainLabel1, 46);
    lv_obj_set_align(ui_RoomsScreenMainLabel1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RoomsScreenMainLabel1, "КОМНАТЫ");
    lv_obj_set_style_text_color(ui_RoomsScreenMainLabel1, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RoomsScreenMainLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RoomsScreenMainLabel1, &ui_font_CalibriBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenKeyboardOpenBtn = lv_button_create(ui_RoomsScreen);
    lv_obj_set_width(ui_RoomsScreenKeyboardOpenBtn, 48);
    lv_obj_set_height(ui_RoomsScreenKeyboardOpenBtn, 36);
    lv_obj_set_x(ui_RoomsScreenKeyboardOpenBtn, 160);
    lv_obj_set_y(ui_RoomsScreenKeyboardOpenBtn, -10);
    lv_obj_set_align(ui_RoomsScreenKeyboardOpenBtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_RoomsScreenKeyboardOpenBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenKeyboardOpenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RoomsScreenKeyboardOpenBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RoomsScreenKeyboardOpenBtn, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenKeyboardOpenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_RoomsScreenKeyboardOpenBtn,
                                  &ui_img_icons_keyboard_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenMicOpenBtn = lv_button_create(ui_RoomsScreen);
    lv_obj_set_width(ui_RoomsScreenMicOpenBtn, 48);
    lv_obj_set_height(ui_RoomsScreenMicOpenBtn, 36);
    lv_obj_set_x(ui_RoomsScreenMicOpenBtn, -160);
    lv_obj_set_y(ui_RoomsScreenMicOpenBtn, -10);
    lv_obj_set_align(ui_RoomsScreenMicOpenBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_RoomsScreenMicOpenBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenMicOpenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RoomsScreenMicOpenBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RoomsScreenMicOpenBtn, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenMicOpenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_RoomsScreenMicOpenBtn, &ui_img_icons_mic_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenTopPanel = lv_obj_create(ui_RoomsScreen);
    lv_obj_set_width(ui_RoomsScreenTopPanel, 458);
    lv_obj_set_height(ui_RoomsScreenTopPanel, 142);
    lv_obj_set_x(ui_RoomsScreenTopPanel, 0);
    lv_obj_set_y(ui_RoomsScreenTopPanel, 96);
    lv_obj_set_align(ui_RoomsScreenTopPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_RoomsScreenTopPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RoomsScreenTopPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_RoomsScreenTopPanel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_RoomsScreenTopPanel, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_RoomsScreenTopPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RoomsScreenTopPanel, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RoomsScreenTopPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RoomsScreenTopPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RoomsScreenTopPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RoomsScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RoomsScreenTopPanel, lv_color_hex(0x2F5B7C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenTopPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenTopPanel, lv_color_hex(0x61C6CE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenTopPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenTopPanel, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RoomsScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RoomsScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RoomsScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RoomsScreenTopPanel, 9, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RoomsScreenHomeButton = lv_button_create(ui_RoomsScreenTopPanel);
    lv_obj_set_width(ui_RoomsScreenHomeButton, 102);
    lv_obj_set_height(ui_RoomsScreenHomeButton, 120);
    lv_obj_set_x(ui_RoomsScreenHomeButton, -144);
    lv_obj_set_y(ui_RoomsScreenHomeButton, 121);
    lv_obj_set_align(ui_RoomsScreenHomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RoomsScreenHomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenHomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenHomeButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenHomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenHomeButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenHomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenHomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenHomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_image_create(ui_RoomsScreenHomeButton);
    lv_image_set_src(ui_Image29, &ui_img_icons_home_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image29, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image29, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_RoomsScreenHomeButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -9);
    lv_obj_set_align(ui_Label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label1, "дом");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenRoomsButton = lv_button_create(ui_RoomsScreenTopPanel);
    lv_obj_set_width(ui_RoomsScreenRoomsButton, 102);
    lv_obj_set_height(ui_RoomsScreenRoomsButton, 120);
    lv_obj_set_x(ui_RoomsScreenRoomsButton, -144);
    lv_obj_set_y(ui_RoomsScreenRoomsButton, 121);
    lv_obj_set_align(ui_RoomsScreenRoomsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RoomsScreenRoomsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenRoomsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenRoomsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenRoomsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenRoomsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenRoomsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenRoomsButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RoomsScreenRoomsButton, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenRoomsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenRoomsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image30 = lv_image_create(ui_RoomsScreenRoomsButton);
    lv_image_set_src(ui_Image30, &ui_img_icons_cards_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image30, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image30, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_RoomsScreenRoomsButton);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, -9);
    lv_obj_set_align(ui_Label36, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label36, "комнаты");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenGroupsButton = lv_button_create(ui_RoomsScreenTopPanel);
    lv_obj_set_width(ui_RoomsScreenGroupsButton, 102);
    lv_obj_set_height(ui_RoomsScreenGroupsButton, 120);
    lv_obj_set_x(ui_RoomsScreenGroupsButton, -144);
    lv_obj_set_y(ui_RoomsScreenGroupsButton, 121);
    lv_obj_set_align(ui_RoomsScreenGroupsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RoomsScreenGroupsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenGroupsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenGroupsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenGroupsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenGroupsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenGroupsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenGroupsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenGroupsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_image_create(ui_RoomsScreenGroupsButton);
    lv_image_set_src(ui_Image31, &ui_img_icons_category_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image31, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image31, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_RoomsScreenGroupsButton);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, -9);
    lv_obj_set_align(ui_Label37, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label37, "группы");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenScenesButton = lv_button_create(ui_RoomsScreenTopPanel);
    lv_obj_set_width(ui_RoomsScreenScenesButton, 102);
    lv_obj_set_height(ui_RoomsScreenScenesButton, 120);
    lv_obj_set_x(ui_RoomsScreenScenesButton, -144);
    lv_obj_set_y(ui_RoomsScreenScenesButton, 121);
    lv_obj_set_align(ui_RoomsScreenScenesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RoomsScreenScenesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenScenesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenScenesButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenScenesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenScenesButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenScenesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenScenesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenScenesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image32 = lv_image_create(ui_RoomsScreenScenesButton);
    lv_image_set_src(ui_Image32, &ui_img_icons_photo_library_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image32, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image32, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image32, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_RoomsScreenScenesButton);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 0);
    lv_obj_set_y(ui_Label38, -9);
    lv_obj_set_align(ui_Label38, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label38, "сцены");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenSettingsButton = lv_button_create(ui_RoomsScreenTopPanel);
    lv_obj_set_width(ui_RoomsScreenSettingsButton, 102);
    lv_obj_set_height(ui_RoomsScreenSettingsButton, 120);
    lv_obj_set_x(ui_RoomsScreenSettingsButton, -144);
    lv_obj_set_y(ui_RoomsScreenSettingsButton, 121);
    lv_obj_set_align(ui_RoomsScreenSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RoomsScreenSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenSettingsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenSettingsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenSettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenSettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image33 = lv_image_create(ui_RoomsScreenSettingsButton);
    lv_image_set_src(ui_Image33, &ui_img_icons_settings_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image33, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image33, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image33, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_RoomsScreenSettingsButton);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 0);
    lv_obj_set_y(ui_Label39, -9);
    lv_obj_set_align(ui_Label39, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label39, "настройки");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenMainPanel = lv_obj_create(ui_RoomsScreen);
    lv_obj_set_width(ui_RoomsScreenMainPanel, 458);
    lv_obj_set_height(ui_RoomsScreenMainPanel, 482);
    lv_obj_set_x(ui_RoomsScreenMainPanel, 0);
    lv_obj_set_y(ui_RoomsScreenMainPanel, 236);
    lv_obj_set_align(ui_RoomsScreenMainPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_RoomsScreenMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RoomsScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RoomsScreenMainPanel, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenMainPanel, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RoomsScreenMainPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RoomsScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RoomsScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RoomsScreenMainPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RoomsScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenRoomsContainer = lv_obj_create(ui_RoomsScreenMainPanel);
    lv_obj_set_width(ui_RoomsScreenRoomsContainer, 458);
    lv_obj_set_height(ui_RoomsScreenRoomsContainer, 430);
    lv_obj_set_x(ui_RoomsScreenRoomsContainer, 0);
    lv_obj_set_y(ui_RoomsScreenRoomsContainer, 58);
    lv_obj_set_align(ui_RoomsScreenRoomsContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_RoomsScreenRoomsContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RoomsScreenRoomsContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_RoomsScreenRoomsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RoomsScreenRoomsContainer, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenRoomsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenRoomsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RoomsScreenRoomsContainer, lv_color_hex(0x2F5B7C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenRoomsContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RoomsScreenRoomsContainer, lv_color_hex(0x61C6CE),
                                  LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomsScreenRoomsContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RoomsScreenRoomsContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_RoomsScreenRoomsContainer);
    lv_obj_set_width(ui_Button6, 400);
    lv_obj_set_height(ui_Button6, 48);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button6, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image35 = lv_image_create(ui_Button6);
    lv_image_set_src(ui_Image35, &ui_img_icons_kitchen_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image35, 0);
    lv_obj_set_y(ui_Image35, 4);
    lv_obj_remove_flag(ui_Image35, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 48);
    lv_obj_set_y(ui_Label42, 12);
    lv_label_set_text(ui_Label42, "кухня");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_RoomsScreenRoomsContainer);
    lv_obj_set_width(ui_Button7, 400);
    lv_obj_set_height(ui_Button7, 48);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button7, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button7, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image36 = lv_image_create(ui_Button7);
    lv_image_set_src(ui_Image36, &ui_img_icons_bedroom_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image36, 0);
    lv_obj_set_y(ui_Image36, 4);
    lv_obj_remove_flag(ui_Image36, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 48);
    lv_obj_set_y(ui_Label43, 12);
    lv_label_set_text(ui_Label43, "спальная комната");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_button_create(ui_RoomsScreenRoomsContainer);
    lv_obj_set_width(ui_Button33, 400);
    lv_obj_set_height(ui_Button33, 48);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button33, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button33, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button33, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button33, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button33, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image37 = lv_image_create(ui_Button33);
    lv_image_set_src(ui_Image37, &ui_img_icons_lounge_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image37, 0);
    lv_obj_set_y(ui_Image37, 4);
    lv_obj_remove_flag(ui_Image37, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 48);
    lv_obj_set_y(ui_Label44, 12);
    lv_label_set_text(ui_Label44, "гостинная");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomsScreenAddRoomBtn = lv_button_create(ui_RoomsScreenMainPanel);
    lv_obj_set_width(ui_RoomsScreenAddRoomBtn, 400);
    lv_obj_set_height(ui_RoomsScreenAddRoomBtn, 48);
    lv_obj_set_x(ui_RoomsScreenAddRoomBtn, 15);
    lv_obj_set_y(ui_RoomsScreenAddRoomBtn, 0);
    lv_obj_add_flag(ui_RoomsScreenAddRoomBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RoomsScreenAddRoomBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsScreenAddRoomBtn, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsScreenAddRoomBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RoomsScreenAddRoomBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RoomsScreenAddRoomBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RoomsScreenAddRoomBtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RoomsScreenAddRoomBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RoomsScreenAddRoomBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RoomsScreenAddRoomBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image34 = lv_image_create(ui_RoomsScreenAddRoomBtn);
    lv_image_set_src(ui_Image34, &ui_img_icons_add_home_work_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image34, 0);
    lv_obj_set_y(ui_Image34, 4);
    lv_obj_remove_flag(ui_Image34, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_RoomsScreenAddRoomBtn);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 48);
    lv_obj_set_y(ui_Label41, 12);
    lv_label_set_text(ui_Label41, "добавить");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RoomsScreenHomeButton, ui_event_RoomsScreenHomeButton, LV_EVENT_ALL, NULL);
    uic_RoomsScreen = ui_RoomsScreen;
    uic_RoomsScreenKeyboardOpenBtn = ui_RoomsScreenKeyboardOpenBtn;
    uic_RoomsScreenMicOpenBtn = ui_RoomsScreenMicOpenBtn;
    uic_RoomsScreenTopPanel = ui_RoomsScreenTopPanel;
    uic_RoomsScreenHomeButton = ui_RoomsScreenHomeButton;
    uic_RoomsScreenRoomsButton = ui_RoomsScreenRoomsButton;
    uic_RoomsScreenGroupsButton = ui_RoomsScreenGroupsButton;
    uic_RoomsScreenScenesButton = ui_RoomsScreenScenesButton;
    uic_RoomsScreenSettingsButton = ui_RoomsScreenSettingsButton;
    uic_RoomsScreenMainPanel = ui_RoomsScreenMainPanel;
    uic_RoomsScreenRoomsContainer = ui_RoomsScreenRoomsContainer;
    uic_RoomsScreenAddRoomBtn = ui_RoomsScreenAddRoomBtn;

}

void ui_RoomsScreen_screen_destroy(void)
{
    if(ui_RoomsScreen) lv_obj_del(ui_RoomsScreen);

    // NULL screen variables
    uic_RoomsScreen = NULL;
    ui_RoomsScreen = NULL;
    ui_RoomsScreenMainLabel1 = NULL;
    uic_RoomsScreenKeyboardOpenBtn = NULL;
    ui_RoomsScreenKeyboardOpenBtn = NULL;
    uic_RoomsScreenMicOpenBtn = NULL;
    ui_RoomsScreenMicOpenBtn = NULL;
    uic_RoomsScreenTopPanel = NULL;
    ui_RoomsScreenTopPanel = NULL;
    uic_RoomsScreenHomeButton = NULL;
    ui_RoomsScreenHomeButton = NULL;
    ui_Image29 = NULL;
    ui_Label1 = NULL;
    uic_RoomsScreenRoomsButton = NULL;
    ui_RoomsScreenRoomsButton = NULL;
    ui_Image30 = NULL;
    ui_Label36 = NULL;
    uic_RoomsScreenGroupsButton = NULL;
    ui_RoomsScreenGroupsButton = NULL;
    ui_Image31 = NULL;
    ui_Label37 = NULL;
    uic_RoomsScreenScenesButton = NULL;
    ui_RoomsScreenScenesButton = NULL;
    ui_Image32 = NULL;
    ui_Label38 = NULL;
    uic_RoomsScreenSettingsButton = NULL;
    ui_RoomsScreenSettingsButton = NULL;
    ui_Image33 = NULL;
    ui_Label39 = NULL;
    uic_RoomsScreenMainPanel = NULL;
    ui_RoomsScreenMainPanel = NULL;
    uic_RoomsScreenRoomsContainer = NULL;
    ui_RoomsScreenRoomsContainer = NULL;
    ui_Button6 = NULL;
    ui_Image35 = NULL;
    ui_Label42 = NULL;
    ui_Button7 = NULL;
    ui_Image36 = NULL;
    ui_Label43 = NULL;
    ui_Button33 = NULL;
    ui_Image37 = NULL;
    ui_Label44 = NULL;
    uic_RoomsScreenAddRoomBtn = NULL;
    ui_RoomsScreenAddRoomBtn = NULL;
    ui_Image34 = NULL;
    ui_Label41 = NULL;

}

void ui_RoomsScreen_screen_relocalize(void)
{
    // label widgets on screen

}
