// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_MainScreen_screen_relocalize(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainScreenMainLabel;
extern lv_obj_t * ui_MainScreenKeyboardOpenBtn;
extern lv_obj_t * ui_MainScreenMicOpenBtn;
extern lv_obj_t * ui_MainScreenTopPanel;
extern lv_obj_t * ui_MainScreenHomeButton;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label3;
extern void ui_event_MainScreenRoomsButton(lv_event_t * e);
extern lv_obj_t * ui_MainScreenRoomsButton;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_MainScreenGroupsButton;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_MainScreenScenesButton;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_MainScreenSettingsButton;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_MainScreenMainPanel;
extern lv_obj_t * ui_MainScreenSensorsContainer;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Image14;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_MainScreenFindDevBtn;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_MainScreenMainLabel;
extern lv_obj_t * uic_MainScreenKeyboardOpenBtn;
extern lv_obj_t * uic_MainScreenMicOpenBtn;
extern lv_obj_t * uic_MainScreenTopPanel;
extern lv_obj_t * uic_MainScreenHomeButton;
extern lv_obj_t * uic_MainScreenRoomsButton;
extern lv_obj_t * uic_MainScreenGroupsButton;
extern lv_obj_t * uic_MainScreenScenesButton;
extern lv_obj_t * uic_MainScreenSettingsButton;
extern lv_obj_t * uic_MainScreenMainPanel;
extern lv_obj_t * uic_MainScreenSensorsContainer;
extern lv_obj_t * uic_MainScreenFindDevBtn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

