// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_MainScreenFindDevBtn;
lv_obj_t * uic_MainScreenSensorsContainer;
lv_obj_t * uic_MainScreenMainPanel;
lv_obj_t * uic_MainScreenSettingsButton;
lv_obj_t * uic_MainScreenScenesButton;
lv_obj_t * uic_MainScreenGroupsButton;
lv_obj_t * uic_MainScreenRoomsButton;
lv_obj_t * uic_MainScreenHomeButton;
lv_obj_t * uic_MainScreenTopPanel;
lv_obj_t * uic_MainScreenMicOpenBtn;
lv_obj_t * uic_MainScreenKeyboardOpenBtn;
lv_obj_t * uic_MainScreenMainLabel;
lv_obj_t * uic_MainScreen;
lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_MainScreenMainLabel = NULL;
lv_obj_t * ui_MainScreenKeyboardOpenBtn = NULL;
lv_obj_t * ui_MainScreenMicOpenBtn = NULL;
lv_obj_t * ui_MainScreenTopPanel = NULL;
lv_obj_t * ui_MainScreenHomeButton = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_MainScreenRoomsButton = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_MainScreenGroupsButton = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_MainScreenScenesButton = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_MainScreenSettingsButton = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_MainScreenMainPanel = NULL;
lv_obj_t * ui_MainScreenSensorsContainer = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_MainScreenFindDevBtn = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Label25 = NULL;
// event funtions
void ui_event_MainScreenRoomsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RoomsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_RoomsScreen_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        swichoffbtnCB(e);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MainScreen, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_MainScreen, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainScreen, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenMainLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenMainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenMainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainScreenMainLabel, 0);
    lv_obj_set_y(ui_MainScreenMainLabel, 46);
    lv_obj_set_align(ui_MainScreenMainLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MainScreenMainLabel, "ДОМ");
    lv_obj_set_style_text_color(ui_MainScreenMainLabel, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainScreenMainLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainScreenMainLabel, &ui_font_CalibriBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenKeyboardOpenBtn = lv_button_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenKeyboardOpenBtn, 48);
    lv_obj_set_height(ui_MainScreenKeyboardOpenBtn, 36);
    lv_obj_set_x(ui_MainScreenKeyboardOpenBtn, 160);
    lv_obj_set_y(ui_MainScreenKeyboardOpenBtn, -10);
    lv_obj_set_align(ui_MainScreenKeyboardOpenBtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_MainScreenKeyboardOpenBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenKeyboardOpenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreenKeyboardOpenBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenKeyboardOpenBtn, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenKeyboardOpenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MainScreenKeyboardOpenBtn,
                                  &ui_img_icons_keyboard_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenKeyboardOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenMicOpenBtn = lv_button_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenMicOpenBtn, 48);
    lv_obj_set_height(ui_MainScreenMicOpenBtn, 36);
    lv_obj_set_x(ui_MainScreenMicOpenBtn, -160);
    lv_obj_set_y(ui_MainScreenMicOpenBtn, -10);
    lv_obj_set_align(ui_MainScreenMicOpenBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_MainScreenMicOpenBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenMicOpenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreenMicOpenBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenMicOpenBtn, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenMicOpenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MainScreenMicOpenBtn, &ui_img_icons_mic_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenMicOpenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenTopPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenTopPanel, 458);
    lv_obj_set_height(ui_MainScreenTopPanel, 142);
    lv_obj_set_x(ui_MainScreenTopPanel, 0);
    lv_obj_set_y(ui_MainScreenTopPanel, 96);
    lv_obj_set_align(ui_MainScreenTopPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MainScreenTopPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MainScreenTopPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_MainScreenTopPanel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_MainScreenTopPanel, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_MainScreenTopPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenTopPanel, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenTopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainScreenTopPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreenTopPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreenTopPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreenTopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainScreenTopPanel, lv_color_hex(0x2F5B7C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenTopPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenTopPanel, lv_color_hex(0x61C6CE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenTopPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenTopPanel, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreenTopPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreenTopPanel, 9, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_MainScreenHomeButton = lv_button_create(ui_MainScreenTopPanel);
    lv_obj_set_width(ui_MainScreenHomeButton, 102);
    lv_obj_set_height(ui_MainScreenHomeButton, 120);
    lv_obj_set_x(ui_MainScreenHomeButton, -144);
    lv_obj_set_y(ui_MainScreenHomeButton, 121);
    lv_obj_set_align(ui_MainScreenHomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenHomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenHomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenHomeButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenHomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenHomeButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenHomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenHomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainScreenHomeButton, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenHomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenHomeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_MainScreenHomeButton);
    lv_image_set_src(ui_Image16, &ui_img_icons_home_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image16, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image16, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_MainScreenHomeButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -9);
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label3, "дом");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenRoomsButton = lv_button_create(ui_MainScreenTopPanel);
    lv_obj_set_width(ui_MainScreenRoomsButton, 102);
    lv_obj_set_height(ui_MainScreenRoomsButton, 120);
    lv_obj_set_x(ui_MainScreenRoomsButton, -144);
    lv_obj_set_y(ui_MainScreenRoomsButton, 121);
    lv_obj_set_align(ui_MainScreenRoomsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenRoomsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenRoomsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenRoomsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenRoomsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenRoomsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenRoomsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenRoomsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenRoomsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_image_create(ui_MainScreenRoomsButton);
    lv_image_set_src(ui_Image17, &ui_img_icons_cards_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image17, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image17, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_MainScreenRoomsButton);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -9);
    lv_obj_set_align(ui_Label21, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label21, "комнаты");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenGroupsButton = lv_button_create(ui_MainScreenTopPanel);
    lv_obj_set_width(ui_MainScreenGroupsButton, 102);
    lv_obj_set_height(ui_MainScreenGroupsButton, 120);
    lv_obj_set_x(ui_MainScreenGroupsButton, -144);
    lv_obj_set_y(ui_MainScreenGroupsButton, 121);
    lv_obj_set_align(ui_MainScreenGroupsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenGroupsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenGroupsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenGroupsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenGroupsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenGroupsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenGroupsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenGroupsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenGroupsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_image_create(ui_MainScreenGroupsButton);
    lv_image_set_src(ui_Image18, &ui_img_icons_category_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image18, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image18, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_MainScreenGroupsButton);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, -9);
    lv_obj_set_align(ui_Label22, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label22, "группы");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenScenesButton = lv_button_create(ui_MainScreenTopPanel);
    lv_obj_set_width(ui_MainScreenScenesButton, 102);
    lv_obj_set_height(ui_MainScreenScenesButton, 120);
    lv_obj_set_x(ui_MainScreenScenesButton, -144);
    lv_obj_set_y(ui_MainScreenScenesButton, 121);
    lv_obj_set_align(ui_MainScreenScenesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenScenesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenScenesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenScenesButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenScenesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenScenesButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenScenesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenScenesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenScenesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_MainScreenScenesButton);
    lv_image_set_src(ui_Image19, &ui_img_icons_photo_library_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image19, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image19, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_MainScreenScenesButton);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -9);
    lv_obj_set_align(ui_Label23, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label23, "сцены");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenSettingsButton = lv_button_create(ui_MainScreenTopPanel);
    lv_obj_set_width(ui_MainScreenSettingsButton, 102);
    lv_obj_set_height(ui_MainScreenSettingsButton, 120);
    lv_obj_set_x(ui_MainScreenSettingsButton, -144);
    lv_obj_set_y(ui_MainScreenSettingsButton, 121);
    lv_obj_set_align(ui_MainScreenSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenSettingsButton, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenSettingsButton, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenSettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenSettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_MainScreenSettingsButton);
    lv_image_set_src(ui_Image20, &ui_img_icons_settings_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image20, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image20, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_MainScreenSettingsButton);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -9);
    lv_obj_set_align(ui_Label24, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label24, "настройки");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenMainPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenMainPanel, 458);
    lv_obj_set_height(ui_MainScreenMainPanel, 482);
    lv_obj_set_x(ui_MainScreenMainPanel, 0);
    lv_obj_set_y(ui_MainScreenMainPanel, 236);
    lv_obj_set_align(ui_MainScreenMainPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MainScreenMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenMainPanel, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenMainPanel, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainScreenMainPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreenMainPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreenMainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenSensorsContainer = lv_obj_create(ui_MainScreenMainPanel);
    lv_obj_set_width(ui_MainScreenSensorsContainer, 458);
    lv_obj_set_height(ui_MainScreenSensorsContainer, 424);
    lv_obj_set_x(ui_MainScreenSensorsContainer, 0);
    lv_obj_set_y(ui_MainScreenSensorsContainer, 64);
    lv_obj_set_align(ui_MainScreenSensorsContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MainScreenSensorsContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainScreenSensorsContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_MainScreenSensorsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenSensorsContainer, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenSensorsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenSensorsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainScreenSensorsContainer, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainScreenSensorsContainer, lv_color_hex(0x2F5B7C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenSensorsContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenSensorsContainer, lv_color_hex(0x61C6CE),
                                  LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenSensorsContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreenSensorsContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_MainScreenSensorsContainer);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 400);
    lv_obj_set_height(ui_Container6, 96);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -1);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_Container6);
    lv_image_set_src(ui_Image24, &ui_img_icons_rele_off_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image24, 6);
    lv_obj_set_y(ui_Image24, 16);
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -36);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "реле");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_RobotoMedium14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 36);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "комната");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_RobotoBold12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_Button18, 36);
    lv_obj_set_height(ui_Button18, 36);
    lv_obj_set_x(ui_Button18, -6);
    lv_obj_set_y(ui_Button18, 0);
    lv_obj_set_align(ui_Button18, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Button18);
    lv_image_set_src(ui_Image14, &ui_img_icons_settings_24dp_61c6ce_fill0_wght200_grad0_opsz24_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_Button15, 48);
    lv_obj_set_height(ui_Button15, 48);
    lv_obj_set_x(ui_Button15, -32);
    lv_obj_set_y(ui_Button15, 0);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_Button15);
    lv_image_set_src(ui_Image15, &ui_img_icons_power_on_circle_48dp_61c6ce_fill1_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_Button16, 48);
    lv_obj_set_height(ui_Button16, 48);
    lv_obj_set_x(ui_Button16, 32);
    lv_obj_set_y(ui_Button16, 0);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_image_create(ui_Button16);
    lv_image_set_src(ui_Image22, &ui_img_icons_power_off_circle_48dp_61c6ce_fill0_wght200_grad0_opsz48_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainScreenFindDevBtn = lv_button_create(ui_MainScreenMainPanel);
    lv_obj_set_width(ui_MainScreenFindDevBtn, 400);
    lv_obj_set_height(ui_MainScreenFindDevBtn, 48);
    lv_obj_set_x(ui_MainScreenFindDevBtn, 15);
    lv_obj_set_y(ui_MainScreenFindDevBtn, 0);
    lv_obj_add_flag(ui_MainScreenFindDevBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenFindDevBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenFindDevBtn, lv_color_hex(0x2F5B7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenFindDevBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MainScreenFindDevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MainScreenFindDevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainScreenFindDevBtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainScreenFindDevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainScreenFindDevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainScreenFindDevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_image_create(ui_MainScreenFindDevBtn);
    lv_image_set_src(ui_Image21, &ui_img_icons_frame_inspect_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 0);
    lv_obj_set_y(ui_Image21, 4);
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_MainScreenFindDevBtn);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 48);
    lv_obj_set_y(ui_Label25, 12);
    lv_label_set_text(ui_Label25, "найти устройства");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x61C6CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_RobotoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainScreenRoomsButton, ui_event_MainScreenRoomsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    uic_MainScreen = ui_MainScreen;
    uic_MainScreenMainLabel = ui_MainScreenMainLabel;
    uic_MainScreenKeyboardOpenBtn = ui_MainScreenKeyboardOpenBtn;
    uic_MainScreenMicOpenBtn = ui_MainScreenMicOpenBtn;
    uic_MainScreenTopPanel = ui_MainScreenTopPanel;
    uic_MainScreenHomeButton = ui_MainScreenHomeButton;
    uic_MainScreenRoomsButton = ui_MainScreenRoomsButton;
    uic_MainScreenGroupsButton = ui_MainScreenGroupsButton;
    uic_MainScreenScenesButton = ui_MainScreenScenesButton;
    uic_MainScreenSettingsButton = ui_MainScreenSettingsButton;
    uic_MainScreenMainPanel = ui_MainScreenMainPanel;
    uic_MainScreenSensorsContainer = ui_MainScreenSensorsContainer;
    uic_MainScreenFindDevBtn = ui_MainScreenFindDevBtn;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    uic_MainScreen = NULL;
    ui_MainScreen = NULL;
    uic_MainScreenMainLabel = NULL;
    ui_MainScreenMainLabel = NULL;
    uic_MainScreenKeyboardOpenBtn = NULL;
    ui_MainScreenKeyboardOpenBtn = NULL;
    uic_MainScreenMicOpenBtn = NULL;
    ui_MainScreenMicOpenBtn = NULL;
    uic_MainScreenTopPanel = NULL;
    ui_MainScreenTopPanel = NULL;
    uic_MainScreenHomeButton = NULL;
    ui_MainScreenHomeButton = NULL;
    ui_Image16 = NULL;
    ui_Label3 = NULL;
    uic_MainScreenRoomsButton = NULL;
    ui_MainScreenRoomsButton = NULL;
    ui_Image17 = NULL;
    ui_Label21 = NULL;
    uic_MainScreenGroupsButton = NULL;
    ui_MainScreenGroupsButton = NULL;
    ui_Image18 = NULL;
    ui_Label22 = NULL;
    uic_MainScreenScenesButton = NULL;
    ui_MainScreenScenesButton = NULL;
    ui_Image19 = NULL;
    ui_Label23 = NULL;
    uic_MainScreenSettingsButton = NULL;
    ui_MainScreenSettingsButton = NULL;
    ui_Image20 = NULL;
    ui_Label24 = NULL;
    uic_MainScreenMainPanel = NULL;
    ui_MainScreenMainPanel = NULL;
    uic_MainScreenSensorsContainer = NULL;
    ui_MainScreenSensorsContainer = NULL;
    ui_Container6 = NULL;
    ui_Image24 = NULL;
    ui_Label12 = NULL;
    ui_Label10 = NULL;
    ui_Button18 = NULL;
    ui_Image14 = NULL;
    ui_Button15 = NULL;
    ui_Image15 = NULL;
    ui_Button16 = NULL;
    ui_Image22 = NULL;
    uic_MainScreenFindDevBtn = NULL;
    ui_MainScreenFindDevBtn = NULL;
    ui_Image21 = NULL;
    ui_Label25 = NULL;

}

void ui_MainScreen_screen_relocalize(void)
{
    // label widgets on screen

}
