// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_ROOMSSCREEN_H
#define UI_ROOMSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RoomsScreen
extern void ui_RoomsScreen_screen_init(void);
extern void ui_RoomsScreen_screen_destroy(void);
extern void ui_RoomsScreen_screen_relocalize(void);
extern lv_obj_t * ui_RoomsScreen;
extern lv_obj_t * ui_RoomsScreenMainLabel1;
extern lv_obj_t * ui_RoomsScreenKeyboardOpenBtn;
extern lv_obj_t * ui_RoomsScreenMicOpenBtn;
extern lv_obj_t * ui_RoomsScreenTopPanel;
extern void ui_event_RoomsScreenHomeButton(lv_event_t * e);
extern lv_obj_t * ui_RoomsScreenHomeButton;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_RoomsScreenRoomsButton;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_RoomsScreenGroupsButton;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_RoomsScreenScenesButton;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_RoomsScreenSettingsButton;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_RoomsScreenMainPanel;
extern lv_obj_t * ui_RoomsScreenRoomsContainer;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_Image41;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_RoomsScreenAddRoomBtn;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Label41;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RoomsScreen;
extern lv_obj_t * uic_RoomsScreenKeyboardOpenBtn;
extern lv_obj_t * uic_RoomsScreenMicOpenBtn;
extern lv_obj_t * uic_RoomsScreenTopPanel;
extern lv_obj_t * uic_RoomsScreenHomeButton;
extern lv_obj_t * uic_RoomsScreenRoomsButton;
extern lv_obj_t * uic_RoomsScreenGroupsButton;
extern lv_obj_t * uic_RoomsScreenScenesButton;
extern lv_obj_t * uic_RoomsScreenSettingsButton;
extern lv_obj_t * uic_RoomsScreenMainPanel;
extern lv_obj_t * uic_RoomsScreenRoomsContainer;
extern lv_obj_t * uic_RoomsScreenAddRoomBtn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

