// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_RoomsScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(
    ui_img_icons_keyboard_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png);    // assets/icons/keyboard_36dp_2F5B7C_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_mic_36dp_2f5b7c_fill0_wght400_grad0_opsz40_png);    // assets/icons/mic_36dp_2F5B7C_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_home_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/home_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_cards_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/cards_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_category_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/category_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_photo_library_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/photo_library_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_settings_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/settings_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_rele_off_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/rele_off_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_settings_24dp_61c6ce_fill0_wght200_grad0_opsz24_png);    // assets/icons/settings_24dp_61C6CE_FILL0_wght200_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_icons_power_on_circle_48dp_61c6ce_fill1_wght200_grad0_opsz48_png);    // assets/icons/power_on_circle_48dp_61C6CE_FILL1_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_power_off_circle_48dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/power_off_circle_48dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_frame_inspect_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/frame_inspect_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_kitchen_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/kitchen_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_bedroom_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/bedroom_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_lounge_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/lounge_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_child_hat_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/child_hat_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_bathtub_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/bathtub_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_wc_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/wc_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_garage_car_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/garage_car_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_add_home_work_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/add_home_work_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_lightbulb_off_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/lightbulb_off_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_power_on_circle_36dp_61c6ce_fill1_wght200_grad0_opsz40_png);    // assets/icons/power_on_circle_36dp_61C6CE_FILL1_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_power_off_circle_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/power_off_circle_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_add_home_work_48dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/add_home_work_48dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_add_home_work_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/add_home_work_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_device_thermostat_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/device_thermostat_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_find_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/find_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_graph_5_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/graph_5_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_group_48dp_2f5b7c_fill0_wght200_grad0_opsz48_png);    // assets/icons/group_48dp_2F5B7C_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_home_work_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/home_work_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_humidity_percentage_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/humidity_percentage_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_keyboard_24dp_2f5b7c_fill0_wght400_grad0_opsz24_png);    // assets/icons/keyboard_24dp_2F5B7C_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_icons_keyboard_48dp_2f5b7c_fill0_wght400_grad0_opsz48_png);    // assets/icons/keyboard_48dp_2F5B7C_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_lightbulb_on_64dp_61c6ce_fill1_wght200_grad0_opsz48_png);    // assets/icons/lightbulb_on_64dp_61C6CE_FILL1_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_mic_48dp_2f5b7c_fill0_wght400_grad0_opsz48_png);    // assets/icons/mic_48dp_2F5B7C_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_power_on_circle_36dp_61c6ce_fill0_wght200_grad0_opsz40_png);    // assets/icons/power_on_circle_36dp_61C6CE_FILL0_wght200_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_icons_rele_on_64dp_61c6ce_fill1_wght200_grad0_opsz48_png);    // assets/icons/rele_on_64dp_61C6CE_FILL1_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_scene_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/scene_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_icons_switch_64dp_61c6ce_fill0_wght200_grad0_opsz48_png);    // assets/icons/switch_64dp_61C6CE_FILL0_wght200_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_bg_gradient_png);    // assets/bg_gradient.png
LV_IMG_DECLARE(ui_img_2073066021);    // assets/mesh-gradient (1).png
LV_IMG_DECLARE(ui_img_1072127791);    // assets/mesh-gradient.png

// FONTS
LV_FONT_DECLARE(ui_font_Calibri12);
LV_FONT_DECLARE(ui_font_Calibri14);
LV_FONT_DECLARE(ui_font_CalibriBold12);
LV_FONT_DECLARE(ui_font_CalibriBold14);
LV_FONT_DECLARE(ui_font_CalibriBold22);
LV_FONT_DECLARE(ui_font_RobotoBlack22);
LV_FONT_DECLARE(ui_font_RobotoBold12);
LV_FONT_DECLARE(ui_font_RobotoBold14);
LV_FONT_DECLARE(ui_font_RobotoBold16);
LV_FONT_DECLARE(ui_font_RobotoBold18);
LV_FONT_DECLARE(ui_font_RobotoBold24);
LV_FONT_DECLARE(ui_font_RobotoCyrInfoLabels);
LV_FONT_DECLARE(ui_font_RobotoCyrTitles);
LV_FONT_DECLARE(ui_font_RobotoMedium12);
LV_FONT_DECLARE(ui_font_RobotoMedium14);
LV_FONT_DECLARE(ui_font_RobotoMedium22);
LV_FONT_DECLARE(ui_font_RobotoMedium36);
LV_FONT_DECLARE(ui_font_RobotoMedium48);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
