// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_MainScreen_screen_relocalize(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainScreenKeyboardOpenBtn;
extern lv_obj_t * ui_MainScreenMicOpenBtn;
extern lv_obj_t * ui_MainScreenMainPanel;
extern lv_obj_t * ui_MainScreenTopPanel;
extern lv_obj_t * ui_MainScreenHomeButton;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label3;
extern void ui_event_MainScreenRoomsButton(lv_event_t * e);
extern lv_obj_t * ui_MainScreenRoomsButton;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_MainScreenGroupsButton;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_MainScreenScenesButton;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_MainScreenDevicesButton;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_MainScreenSettingsButton;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_MainScreenSensorsContainer;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_LampSensorComp2;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Image12;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_devicecontainer;
extern lv_obj_t * ui_DeviceCommenContainer;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_DeviceEndpointCommentBtnContainer2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_DeviceIeeeContainer;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_DeviceShortContainer;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_DeviceZclVerContainer;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_DeviceManufContainer;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_DeviceModelContainer;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_DevicePowerSourceContainer;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_DeviceEndpointsContainer;
extern lv_obj_t * ui_DeviceEndpointsContainerLabel;
extern lv_obj_t * ui_DeviceEndpointContainer;
extern lv_obj_t * ui_DeviceEndpointContainerEPnumCheckCont;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_DeviceEndpointCommentContainer;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_DeviceEndpointCommentBtnContainer;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_DeviceEndpointDevTypeContainer;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_DeviceEndpointContainerInpClLabel;
extern lv_obj_t * ui_DeviceEndpointInputClustersContainer;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_DeviceEndpointOutputClustersContainer;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_LampSensorComp3;
extern lv_obj_t * ui_LampSensorComp4;
extern lv_obj_t * ui_LampSensorComp5;
extern lv_obj_t * ui_LampSensorComp6;
extern lv_obj_t * ui_LampSensorComp7;
extern lv_obj_t * ui_LampSensorComp8;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_MainScreenMainLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_MainScreenKeyboardOpenBtn;
extern lv_obj_t * uic_MainScreenMicOpenBtn;
extern lv_obj_t * uic_MainScreenMainPanel;
extern lv_obj_t * uic_MainScreenTopPanel;
extern lv_obj_t * uic_MainScreenHomeButton;
extern lv_obj_t * uic_MainScreenRoomsButton;
extern lv_obj_t * uic_MainScreenGroupsButton;
extern lv_obj_t * uic_MainScreenScenesButton;
extern lv_obj_t * uic_MainScreenDevicesButton;
extern lv_obj_t * uic_MainScreenSettingsButton;
extern lv_obj_t * uic_MainScreenSensorsContainer;
extern lv_obj_t * uic_devicecontainer;
extern lv_obj_t * uic_DeviceCommenContainer;
extern lv_obj_t * uic_DeviceIeeeContainer;
extern lv_obj_t * uic_DeviceShortContainer;
extern lv_obj_t * uic_DeviceManufContainer;
extern lv_obj_t * uic_DevicePowerSourceContainer;
extern lv_obj_t * uic_DeviceEndpointsContainer;
extern lv_obj_t * uic_DeviceEndpointContainer;
extern lv_obj_t * uic_DeviceEndpointContainerEPnumCheckCont;
extern lv_obj_t * uic_DeviceEndpointCommentContainer;
extern lv_obj_t * uic_DeviceEndpointCommentBtnContainer;
extern lv_obj_t * uic_DeviceEndpointDevTypeContainer;
extern lv_obj_t * uic_DeviceEndpointContainerInpClLabel;
extern lv_obj_t * uic_DeviceEndpointInputClustersContainer;
extern lv_obj_t * uic_DeviceEndpointOutputClustersContainer;
extern lv_obj_t * uic_MainScreenMainLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

